---
apiVersion: v1
kind: Pod
type: Recreate
hostNetwork: true
serviceAccountName: kubedoom
metadata:
  name: kubedoom
  labels:
    app: kubedoom
spec:
  containers:
    - image: storaxdev/kubedoom:0.5.0
      name: kubedoom
      ports:
        - containerPort: 5900
          protocol: TCP


